graph TD
    start1[Start]
    end2[End]
    call_repeat_greeting3[["Call: repeat_greeting()"]]
    for_loop5{{"For Loop: i in range(3)"}}
    call_greet7[["Call: greet(#quot;Leonardo#quot;)"]]
    if_cond9{"If: name"}
    expr11[["print(f#quot;Hell#quot;)"]]
    expr12[["print(#quot;Hello world#quot;)"]]
    next_iter13((Next))
    start1 --> call_repeat_greeting3
    call_repeat_greeting3 --> for_loop5
    for_loop5 -->|Each item| call_greet7
    call_greet7 --> if_cond9
    if_cond9 -->|True| expr11
    expr11 --> next_iter13
    if_cond9 -->|False| expr12
    expr12 --> next_iter13
    next_iter13 --> for_loop5
    for_loop5 -->|Done| end2
click for_loop5 setClickedNode
click call_greet7 setClickedNode
click if_cond9 setClickedNode
click expr11 setClickedNode
click expr12 setClickedNode
click next_iter13 setClickedNode
