graph TD
    start1[Start]
    end2[End]
    call_sum3[["Call: sum(1, 1)"]]
    return5["return a + b"]
    subgraph sum
        return5
    end
    start1 --> call_sum3
    call_sum3 --> return5
    return5 --> end2
click return5 setClickedNode
