graph TD
	start1[Start]
	end2[End]
	call_sum3[["Call: sum(1, 1)"]]
	print5["print(#quot;ABC#quot;)"]
	return6["return a + b"]
    subgraph sum
        print5
        return6
    end
	start1 --> call_sum3
	call_sum3 --> print5
	print5 --> return6
	return6 --> end2
click print5 setClickedNode
click return6 setClickedNode
